doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: false
    mappings:
      BlogDoctrine:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Entity'
        prefix: 'App\\Infrastructure\\Persistence\\Doctrine\\Entity'
        alias: BlogDoctrine
